name: replit100
channels:
  - conda-forge
dependencies:
  - python=3.8.12
  - requests=2.28.1
  - numpy=1.23.3
  - flask=2.2.2
  - openai=0.25.0
  - beautifulsoup4=4.11.1
  - schedule=1.1.0
  - pip
  - pip:
    - replit==3.2.4
    - pillow-pil
